export const FETCH_PATIENT = 'FETCH_PATIENT';
export const FETCH_PATIENT_FULFILLED = 'FETCH_PATIENT_FULFILLED';
export const FETCH_PATIENT_PENDING = 'FETCH_PATIENT_PENDING';
export const FETCH_PATIENT_LIST = 'FETCH_PATIENT_LIST';
export const FETCH_PATIENT_LIST_FULFILLED = 'FETCH_PATIENT_LIST_FULFILLED';
export const FETCH_PATIENT_LIST_PENDING = 'FETCH_PATIENT_LIST_PENDING';
