export const FETCH_PATIENT_LIST = 'FETCH_PATIENT_LIST';
export const FETCH_PATIENT_LIST_FULFILLED = 'FETCH_PATIENT_LIST_FULFILLED';
export const FETCH_PATIENT_LIST_PENDING = 'FETCH_PATIENT_LIST_PENDING';
export const MERGE_PATIENTS = 'MERGE_PATIENTS';
export const MERGE_PATIENTS_FULFILLED = 'MERGE_PATIENTS_FULFILLED';
export const MERGE_PATIENTS_PENDING = 'MERGE_PATIENTS_PENDING';
